# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Build
      run: go build -v ./...

    - name: Lint install
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2

    - name: Lint
      run: golangci-lint run --timeout 5m

    - name: Test
      run: make test
